id:273
user_name:172.26.40.155
user_id:172.26.40.1-fd619819a3174031
script:1 - Pump Control
start_time:1552835745602
command:/eve/scripts/webui-sc/mpumptimed.py all Drug,Media 1
exit_code:0
>>>>>  OUTPUT STARTED <<<<<
EVEs Selected:
[1, 2, 3]
Started
Pin Lists:
[20, 17, 21]
[0, 1, 2]
[8, 9, 10]
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/eve/scripts/webui-sc/mpumptimed.py", line 85, in runner
    pins[P_nut_pins].value = True
  File "/usr/local/lib/python3.5/dist-packages/adafruit_mcp230xx.py", line 145, in value
    self._mcp.gpio = _enable_bit(self._mcp.gpio, self._pin)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_mcp230xx.py", line 315, in gpio
    self._write_u16le(_MCP23017_GPIOA, val)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_mcp230xx.py", line 288, in _write_u16le
    i2c.write(_BUFFER, end=3)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_bus_device/i2c_device.py", line 112, in write
    self.i2c.writeto(self.device_address, buf, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/busio.py", line 64, in writeto
    return self._i2c.writeto(address, memoryview(buffer)[start:end], stop=stop)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 38, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_PureIO/smbus.py", line 244, in write_bytes
    self._device.write(buf)
OSError: [Errno 121] Remote I/O error
Done!
Done!
