id:276
user_name:172.26.40.155
user_id:172.26.40.1-fd619819a3174031
script:Pumps and LED Off
start_time:1552835866762
command:su -c ./pumpsledoff.py -s /bin/sh vishhvaan
exit_code:0
>>>>>  OUTPUT STARTED <<<<<
EVEs Enabled:
[1, 2, 3]
Started
Pin Lists:
[20, 17, 21, 25]
Done!
[0, 1, 2, 3]
[8, 9, 10, 11]
Process Process-2:
Process Process-3:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "./pumpsledoff.py", line 64, in runner
    pins[pin].value = False
  File "/usr/local/lib/python3.5/dist-packages/adafruit_mcp230xx.py", line 147, in value
    self._mcp.gpio = _clear_bit(self._mcp.gpio, self._pin)
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/adafruit_mcp230xx.py", line 311, in gpio
    return self._read_u16le(_MCP23017_GPIOA)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_mcp230xx.py", line 277, in _read_u16le
    i2c.write(_BUFFER, end=1, stop=False)
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_bus_device/i2c_device.py", line 112, in write
    self.i2c.writeto(self.device_address, buf, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/busio.py", line 64, in writeto
    return self._i2c.writeto(address, memoryview(buffer)[start:end], stop=stop)
  File "./pumpsledoff.py", line 64, in runner
    pins[pin].value = False
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 38, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
  File "/usr/local/lib/python3.5/dist-packages/adafruit_mcp230xx.py", line 147, in value
    self._mcp.gpio = _clear_bit(self._mcp.gpio, self._pin)
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_PureIO/smbus.py", line 244, in write_bytes
    self._device.write(buf)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_mcp230xx.py", line 315, in gpio
    self._write_u16le(_MCP23017_GPIOA, val)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_mcp230xx.py", line 288, in _write_u16le
    i2c.write(_BUFFER, end=3)
OSError: [Errno 121] Remote I/O error
  File "/usr/local/lib/python3.5/dist-packages/adafruit_bus_device/i2c_device.py", line 112, in write
    self.i2c.writeto(self.device_address, buf, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/busio.py", line 64, in writeto
    return self._i2c.writeto(address, memoryview(buffer)[start:end], stop=stop)
  File "/usr/local/lib/python3.5/dist-packages/adafruit_blinka/microcontroller/generic_linux/i2c.py", line 38, in writeto
    self._i2c_bus.write_bytes(address, buffer[start:end])
  File "/usr/local/lib/python3.5/dist-packages/Adafruit_PureIO/smbus.py", line 244, in write_bytes
    self._device.write(buf)
OSError: [Errno 121] Remote I/O error
